# Generated by Django 2.1.2 on 2018-11-10 09:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181109_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 10, 9, 25, 45, 333732, tzinfo=utc)),
        ),
    ]
